'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace CustomRibbonControl.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(CustomRibbonControl.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(CustomRibbonControl.Properties.Resources).Assembly)
                    CustomRibbonControl.Properties.Resources.resourceMan = temp
                End If

                Return CustomRibbonControl.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return CustomRibbonControl.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                CustomRibbonControl.Properties.Resources.resourceCulture = value
            End Set
        End Property

        Friend Shared ReadOnly Property Code_Central As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("Code_Central", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property Contact_Us As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("Contact_Us", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property ExportGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("ExportGraphicLarge", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property ExportGraphicLarge1 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("ExportGraphicLarge1", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property ExportMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("ExportMhtLarge", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property ExportRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("ExportRtfLarge", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property ExportRtfLarge1 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("ExportRtfLarge1", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property ExportXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("ExportXlsLarge", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property MultiplePagesLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("MultiplePagesLarge", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property Online_Help As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("Online_Help", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property Online_Help1 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("Online_Help1", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PageMarginsModerate As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("PageMarginsModerate", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PageMarginsWide As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("PageMarginsWide", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PaperSizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("PaperSizeLarge", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PrintDirectLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("PrintDirectLarge", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property XtraBars As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("XtraBars", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property Yellow As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomRibbonControl.Properties.Resources.ResourceManager.GetObject("Yellow", CustomRibbonControl.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
